version: 0.2
env:
  secrets-manager:
    ARTIFACTORY_EMAIL: 'prod/codebuild/jfrog:ARTIFACTORY_EMAIL'
    ARTIFACTORY_ENCRYPTED_PASS: 'prod/codebuild/jfrog:ARTIFACTORY_ENCRYPTED_PASS'
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "installing JFrog CLI"
      - wget -qO - https://releases.jfrog.io/artifactory/api/gpg/key/public | apt-key add -
      - echo "deb https://releases.jfrog.io/artifactory/jfrog-debs xenial contrib" | tee -a /etc/apt/sources.list
      - apt update
      - apt install -y jfrog-cli
      - jfrog -v
  pre_build:
    on-failure: ABORT
    commands:
      - echo Entering pre_build phase...
      - echo setup environment for ${CODEBUILD_GIT_TAG}
      - export CODEBUILD_GIT_TAG="$(git describe --tags --exact-match 2>/dev/null)"
      - echo "adding jfrog config"
      - jfrog config add ${JFROG_SERVER_ID} --artifactory-url ${ARTIFACTORY_URL} --user ${ARTIFACTORY_EMAIL} --apikey ${ARTIFACTORY_ENCRYPTED_PASS} --interactive=false
      - jfrog config use ${JFROG_SERVER_ID}
      - jfrog rt npm-config --server-id-resolve ${JFROG_SERVER_ID} --server-id-deploy ${JFROG_SERVER_ID} --repo-resolve ${NPM_BASE_REPO} --repo-deploy ${NPM_REPO}
      - jfrog rt ping
  build:
    on-failure: ABORT
    commands:
      - cd ./packages/material-ui-icons/
      - echo install NPM packages for ${BUILD_NAME}
      - npm i
      - echo building ${BUILD_NAME}
      - npm run build --env=production
      - echo publishing ${CODEBUILD_GIT_TAG} to npm
      - npm --no-git-tag-version version v5.0.0-alpha.36
      - jfrog rt npm-publish --build-name=${BUILD_NAME} --build-number=v5.0.0-alpha.36
      - echo "successfully pushed the npm package to Jfrog"
